name: Run Bazel build

on:
  workflow_dispatch:
  push:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Bazelisk
      run: npm install -g @bazel/bazelisk

    - name: Run files through Bazelisk
      run: bazelisk run main:hello_world
