name: Run Bazel build

on:
  workflow_dispatch:
  push:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run files through Bazel
      run: bazel run :main

  build:
    runs-on: windows-latest
    steps:
      - name: Install Bazel
        run: choco install bazel
        
      - name: Verify Bazel installation
        run: bazel --version
        
      - name: Run files through Bazel
        run: bazel run :main
